# AUTOGENERATED! DO NOT EDIT! File to edit: 05_aligning_the_embeddings_using_vecmap.ipynb (unless otherwise specified).

__all__ = ['embs_to_txt', 'txt_to_embs']

# Cell
def embs_to_txt(vocab, embeddings, fname):
    '''writes embeddings to txt file in word2vec format'''
    lines = []
    lines.append(f'{len(vocab)} {embeddings.shape[1]}\n')
    for word, t in zip(vocab, embeddings):
        word = re.subn('\n', '', word)[0]
        lines.append(f"{word} {' '.join([str(datum.item()) for datum in t])}\n")
    with open(fname, 'w') as f:
        f.writelines(lines)

# Cell

def txt_to_embs(fname):
    with open(fname, 'r') as f:
        lines = f.readlines()
    vocab = []
    embs = []
    for line in lines[1:]:
        l = line.split()
        vocab.append(l[0])
        embs.append(np.array([float(s) for s in l[1:]]))
    return vocab, np.stack(embs)