# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"download_ebook": "00_data.ipynb"}

modules = ["data.py"]

doc_url = "https://earthspecies.github.io/language_induction/"

git_url = "https://github.com/earth_species/language_induction/tree/master/"

def custom_doc_links(name): return None