# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"split_file_into_chunks": "01_train_LM_en.ipynb",
         "PermuteEmbedding": "01_train_LM_en.ipynb",
         "pAWD_LSTM": "01_train_LM_en.ipynb",
         "opt": "04a_LM_with_normalized_embeddings_mixer_softmax.ipynb",
         "drops": "04a_LM_with_normalized_embeddings_mixer_softmax.ipynb",
         "config": "04a_LM_with_normalized_embeddings_mixer_softmax.ipynb",
         "optimize_permutation": "01_train_LM_en.ipynb",
         "optimize_model": "01_train_LM_en.ipynb",
         "aza_loss": "01_train_LM_en.ipynb",
         "hitInTopN": "01_train_LM_en.ipynb",
         "print_synonyms": "01_train_LM_en.ipynb",
         "get_en_es_dict": "03_translate_en_to_es.ipynb",
         "top_n_translation_acc": "03_translate_en_to_es.ipynb",
         "PermuteEmbeddingNorm": "04_LM_with_normalized_embeddings.ipynb",
         "p_normAWD_LSTM": "04_LM_with_normalized_embeddings.ipynb",
         "PermuteEmbeddingMixerNorm": "04a_LM_with_normalized_embeddings_mixer_softmax.ipynb",
         "p_mixer_normAWD_LSTM": "04a_LM_with_normalized_embeddings_mixer_softmax.ipynb",
         "embs_to_txt": "05_aligning_the_embeddings_using_vecmap.ipynb",
         "txt_to_embs": "05_aligning_the_embeddings_using_vecmap.ipynb"}

modules = ["core.py",
           "data.py",
           "decoder_head/core.py"]

doc_url = "https://earthspecies.github.io/decoder_head/"

git_url = "https://github.com/earth_species/decoder_head/tree/master/"

def custom_doc_links(name): return None
